### ISSUE TITLE
GUI & Widgets

### ISSUE THREAD

**Issue by dumblob** [til-lang/til#15]
By sole accident I came across https://www.nemethi.de/ and the code together with the [screenshots](https://www.nemethi.de/tablelist/screenshots.html ) persuaded me to post it here as potential candidates for porting these to Til.

Or in case Til would rather have Web-first support, then at least the API (modulo [liveness](https://github.com/til-lang/til/issues/8 )) of the linked widgets might be worth exploring and taking inspiration from :wink:.

**Comment by cleberzavadniak** [comment]
Well, now we have [til-tcl](https://github.com/til-lang/til-tcl), a package I created basically with the purpose of having Tk working with Til.

**Comment by dumblob** [comment]
Very well, sounds promising!
