### ISSUE TITLE
Idea: use "extraction" also for setting the corresponding value

### ISSUE THREAD

**Issue by dumblob** [til-lang/til#4]
It seems that e.g. for a `dict` the syntax for setting a value is "special" - worse, it's specific to `dict` and no other type.

I was thinking whether the *extraction* syntax could be somehow leveraged not only for reading (ranges of) values, but also generally for setting those values.

**Comment by cleberzavadniak** [comment]
I wouldn't use the same syntax as Extractions, but maybe using the same `set` syntax...

```tcl
set d [dict]
set $d key value
```

Hey! That's not difficult to implement! `set` could check if argument1 is an NameAtom and, if not, call `argument1.set(other_arguments)`. And that would benefit third-party types a lot.

**Comment by dumblob** [comment]
Is `set` extensible_to/usable_with user-defined "types" also?

**Comment by cleberzavadniak** [comment]
Not yet. But making it check the type of the first argument and calling `firstArgument.set(...)` in some cases will do the job.

**Comment by cleberzavadniak** [comment]
Implemented in 0.1.2.
